### ISSUE TITLE
either-or doesn't check both options, just the second one

### ISSUE THREAD

**Issue by imjoshdean** [canjs/can-stache-converters#32]
Seems like an oversight in development.

https://github.com/canjs/can-stache-converters/blob/master/can-stache-converters.js#L64

**Comment by justinbmeyer** [comment]
@imjoshdean What behavior do you want?

```
stache.registerConverter("either-or", {
	get: function(chosen, a, b){
		return b !== chosen();
	},
	set: function(newVal, chosen, a, b){
		chosen(newVal ? a : b);
	}
});
```

What should the result of `get` be depending on `a`, `b`, `chosen`?  Currently, it seems to me that unless `b` is chosen, the answer will be `true`.  It will be `false` only if `b` is chosen.  We can really ignore `a` in this case.  

Here's the basic chart:

| a  | b | chosen | get |
| ------------- | ------------- | ------------- | ------------- |
| 1 | 2 | 1 | true |
| 1 | 2 | 2 | false |

I think what we need to figure out is what happens when `chosen` doesn't match `a` or `b`.  Currently, `get` is going to be `true`:

| a  | b | chosen | get |
| ------------- | ------------- | ------------- | ------------- |
| 1 | 2 | null | true |
| 1 | 2 | undefined | true |

You could reverse this behavior like:

```
<input {($checked)}="not( ~either-or(b, a) )"
```

Or we could create another helper that switches the "default".

**Comment by justinbmeyer** [comment]
For this issue, it would be good to provide the chart above.

**Comment by phillipskevin** [comment]
We should document https://github.com/canjs/can-stache-converters/issues/32#issuecomment-295037717 in the either-or docs.

**Comment by Alfredo-Delgado** [comment]
@justinbmeyer @phillipskevin @matthewp @imjoshdean I've updated the documentation, but I think this is how this feature should behave:

| property | initial _~chosen_ value | _a_: truthy case  | _b_: falsey  case | either-or return | final _~chosen_ value |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| wantSome | Yes | Yes | No | true | Yes
| wantSome | No | Yes | No | false | No
| wantSome | Maybe | Yes | No | false | No
| wantSome | undefined | Yes | No | false | No
| wantSome | null | Yes | No | false | No

This is how it currently behaves:

| property | initial _~chosen_ value | _a_: truthy case  | _b_: falsey  case | either-or return | final _~chosen_ value |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| wantSome | Yes | Yes | No | true | Yes
| wantSome | No | Yes | No | false | No
| wantSome | **Maybe** | Yes | No | **true** | **Maybe**
| wantSome | **undefined** | Yes | No | **true** | **undefined**
| wantSome | **null** | Yes | No | **true** | **null**

**Comment by Alfredo-Delgado** [comment]
Will implement:

| property | initial _~chosen_ value | _a_: truthy case  | _b_: falsey  case | either-or return | final _~chosen_ value |
| ------------- | ------------- | ------------- | ------------- | ------------- | ------------- |
| wantSome | Yes | Yes | No | true | Yes
| wantSome | No | Yes | No | false | No
| wantSome | Maybe | Yes | No | undefined* | Maybe
| wantSome | undefined | Yes | No |undefined* | undefined
| wantSome | null | Yes | No | undefined* | null

_* Warning will be logged that chosen does not match a or b._
